imports:
    - { resource: config.yml }

parameters:
    limit_per_page: 10

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# 生产环境通过swift mailer发送异常信息到指定邮箱的配置
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
        deduplicated:
            type: deduplication   # 1分钟只发送1次
            handler: swift
        swift:
            type: swift_mailer
            from_email: '%mailer_user%'
            to_email: '%admin_email%'
            subject: 'kernel exception'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
