imports:
    - { resource: config.yml }

parameters:
    limit_per_page: 10

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

twig:
    auto_reload: true

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/main.%kernel.environment%.log'
            level: debug
            max_files: 10
            filename_format: '{filename}.{date}'
            date_format: 'Ymd'
            channels: ['!event', '!request', '!doctrine', '!service']

        request:
            type: rotating_file
            path: '%kernel.logs_dir%/request.%kernel.environment%.log'
            level: debug
            max_files: 10
            filename_format: '{filename}.{date}'
            date_format: 'Ymd'
            channels: [request]

        doctrine:
            type: rotating_file
            path: '%kernel.logs_dir%/doctrine.%kernel.environment%.log'
            level: debug
            max_files: 10
            filename_format: '{filename}.{date}'
            date_format: 'Ymd'
            channels: [doctrine]

        service:
            type: rotating_file
            path: '%kernel.logs_dir%/service.%kernel.environment%.log'
            level: debug
            max_files: 10
            filename_format: '{filename}.{date}'
            date_format: 'Ymd'
            channels: [service]

        console:
            type: console
            channels: ['!event', '!doctrine']

#swiftmailer:
#    delivery_addresses: ['me@example.com']
