mary_web_homepage:
    path: /
    defaults: { _controller: MaryWebBundle:Default:index }

login:
    path: /login
    defaults: { _controller: MaryWebBundle:Security:login }

register:
    path: /register
    defaults: { _controller: MaryWebBundle:Security:register }

logout:
    path: /logout

hello_page:
    path: /hello/{name}
    defaults: { _controller: MaryWebBundle:Default:hello }

show_message:
    path: /show/message/{message}
    defaults: { _controller: MaryWebBundle:Default:showMessage }

config_index:
    path: /config
    defaults: { _controller: MaryWebBundle:Config:index }

config_show_parameter:
    path: /config/show/parameter/{key}
    defaults: { _controller: MaryWebBundle:Config:showParameter }

db_index:
    path: /db
    defaults: { _controller: MaryWebBundle:Database:index }

db_add_user:
    path: /db/add/user
    defaults: { _controller: MaryWebBundle:Database:addUser }

db_add_author:
    path: /db/add/author
    defaults: { _controller: MaryWebBundle:Database:addAuthor }

db_add_book:
    path: /db/add/book
    defaults: { _controller: MaryWebBundle:Database:addBook }

db_show_author_books:
    path: /db/show/author/{authorId}/books
    defaults: { _controller: MaryWebBundle:Database:showAuthorBooks }

db_update_user_age:
    path: /db/update/user/{userId}/age/{age}
    defaults: { _controller: MaryWebBundle:Database:updateUserAge }

db_update_user_password:
    path: /db/update/user/{userId}/password
    defaults: { _controller: MaryWebBundle:Database:updateUserPassword }

db_remove_user:
    path: /db/remove/user/{userId}
    defaults: { _controller: MaryWebBundle:Database:removeUser }

db_remove_author:
    path: /db/remove/author/{authorId}
    defaults: { _controller: MaryWebBundle:Database:removeAuthor }

db_find_user_by_raw_sql:
    path: /db/find/user/{userId}/by/raw/sql
    defaults: { _controller: MaryWebBundle:Database:findUserByRawSql }

extension_index:
    path: /extension
    defaults: { _controller: MaryWebBundle:Extension:index }

extension_common:
    path: /extension/common
    defaults: { _controller: MaryWebBundle:Extension:common }

extension_custom:
    path: /extension/custom
    defaults: { _controller: MaryWebBundle:Extension:custom }

extension_fragment:
    path: /extension/fragment
    defaults: { _controller: MaryWebBundle:Extension:fragment }

event_index:
    path: /event
    defaults: { _controller: MaryWebBundle:Event:index }

form_index:
    path: /form
    defaults: { _controller: MaryWebBundle:Form:index }

from_create_user:
    path: /form/create/user
    defaults: { _controller: MaryWebBundle:Form:createUser }

from_register:
    path: /form/register
    defaults: { _controller: MaryWebBundle:Form:register }

from_login:
    path: /form/login
    defaults: { _controller: MaryWebBundle:Form:login }

logger_index:
    path: /logger
    defaults: { _controller: MaryWebBundle:Logger:index }

mailer_index:
    path: /mailer
    defaults: { _controller: MaryWebBundle:Mailer:index }

mailer_test:
    path: /mailer/test
    defaults: { _controller: MaryWebBundle:Mailer:test }

request_index:
    path: /request
    defaults: { _controller: MaryWebBundle:Request:index }

request_curl:
    path: /request/curl
    defaults: { _controller: MaryWebBundle:Request:curl }

request_error:
    path: /request/error
    defaults: { _controller: MaryWebBundle:Request:error }

response_json:
    path: /response/json
    defaults: { _controller: MaryWebBundle:Response:json }

response_json_success:
    path: /response/json/success
    defaults: { _controller: MaryWebBundle:Response:jsonSuccess }

response_json_error:
    path: /response/json/error
    defaults: { _controller: MaryWebBundle:Response:jsonError }

serializer_index:
    path: /serializer
    defaults: { _controller: MaryWebBundle:Serializer:index }

serializer_serialize:
    path: /serializer/serialize/{format}
    defaults: { _controller: MaryWebBundle:Serializer:serialize, format: 'json' }

serializer_normalize:
    path: /serializer/normalize
    defaults: { _controller: MaryWebBundle:Serializer:normalize }

service_index:
    path: /service
    defaults: { _controller: MaryWebBundle:Service:index }

service_call:
    path: /service/call
    defaults: { _controller: MaryWebBundle:Service:call }

test_admin:
    path: /test/admin
    defaults: { _controller: MaryWebBundle:Test:admin }

translator_index:
    path: /translator
    defaults: { _controller: MaryWebBundle:Translator:index }

translator_use_domain:
    path: /translator/use/domain
    defaults: { _controller: MaryWebBundle:Translator:useDomain }

translator_pass_param:
    path: /translator/pass/param/{name}
    defaults: { _controller: MaryWebBundle:Translator:passParam }

translator_force_locale:
    path: /translator/force/locale/{locale}
    defaults: { _controller: MaryWebBundle:Translator:forceLocale }

translator_use_in_view:
    path: /translator/use/in/view/{mode}
    defaults: { _controller: MaryWebBundle:Translator:useInView, mode: 'basic' }

user_index:
    path: /user/index
    defaults: { _controller: MaryWebBundle:User:index }