services:
    mary.webbundle.hello:
        class: Mary\WebBundle\Service\HelloService
        arguments:
            $language: 'en'
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: service }

    mary.webbundle.curl:
        class: Mary\Common\Libs\Curl\Curl
        auguments:
            $baseUrl: ''

    mary.webbundle.user_subscriber:
        class: Mary\WebBundle\Event\Subscriber\UserSubscriber
        arguments:
            $logger: '@logger'
        tags:
            - { name: kernel.event_subscriber }

    mary.webbundle.web_extension:
        class: Mary\WebBundle\Twig\Extension\WebExtension
        public: false
        tags:
            - { name: twig.extension }