parameters:

services:
    mary.webbundle.exception_listener:
        class: Mary\WebBundle\Listener\KernelExceptionListener
        arguments: ['@logger', '@mailer']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    mary.webbundle.user_subscriber:
        class: Mary\WebBundle\Event\Subscriber\UserSubscriber
        arguments:
            $logger: '@logger'
        tags:
            - { name: kernel.event_subscriber }

    mary.webbundle.logout_success_handler:
        class: Mary\WebBundle\Handler\LogoutSuccessHandler
        parent: security.logout.success_handler

    mary.webbundle.hello_service:
        class: Mary\WebBundle\Service\HelloService
        arguments: ['%locale%', '@logger', '@request_stack']
        tags:
            - { name: monolog.logger, channel: service }

    mary.webbundle.curl_service:
        class: Mary\Common\Libs\Curl\Curl
        auguments:
            $baseUrl: ''

    mary.webbundle.assets_service:
        class: Mary\WebBundle\Service\AssetsService
        arguments: ['@request_stack', '%assets_version%']

    mary.webbundle.uploader_service:
        class: Mary\WebBundle\Service\UploaderService
        arguments:
            $uploadsDir: '%uploads_dir%'
            $options:
                thumb_switch: true
                thumb_size: [{width: 120, height: 90}, {width: 200, height: 150}]

    mary.webbundle.web_extension:
        class: Mary\WebBundle\Twig\Extension\WebExtension
        arguments:
            $options:
                kernel_env: '%kernel.environment%'
        public: false
        tags:
            - { name: twig.extension }

    mary.webbundle.assets_extension:
        class: Mary\WebBundle\Twig\Extension\AssetsExtension
        arguments: ['@mary.webbundle.assets_service']
        public: false
        tags:
            - { name: twig.extension }